# Generated by Django 6.0 on 2025-12-08 15:40

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(upload_to=home.models.user_directory_path),
        ),
    ]
